-- ============================================================
-- ReBe ReFresh — Admin CRM Phase 1
-- Adds role-based access control + customer notes audit trail.
-- Run this in Supabase SQL Editor.
-- ============================================================

-- 1. Role enum + user_roles table
-- ------------------------------------------------------------
CREATE TYPE app_role AS ENUM ('admin', 'staff');

CREATE TABLE user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role app_role NOT NULL DEFAULT 'staff',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, role)
);

CREATE INDEX idx_user_roles_user ON user_roles(user_id);


-- 2. customer_notes — audit-trailed per-customer notes
-- ------------------------------------------------------------
CREATE TABLE customer_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  author_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  author_email TEXT,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_customer_notes_customer ON customer_notes(customer_id);
CREATE INDEX idx_customer_notes_created ON customer_notes(created_at DESC);


-- 3. Helper — is the calling user an admin or staff member?
-- SECURITY DEFINER lets RLS policies call this without
-- needing the calling user to SELECT from user_roles directly.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION is_admin_or_staff()
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM user_roles
    WHERE user_id = auth.uid()
      AND role IN ('admin', 'staff')
  );
$$;

CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM user_roles
    WHERE user_id = auth.uid() AND role = 'admin'
  );
$$;


-- 4. RLS on existing data tables — admin/staff can read
-- IMPORTANT: existing RPCs (register_for_program, submit_cohort_signup)
-- are SECURITY DEFINER so they bypass RLS and keep working.
-- Service role (Stripe webhook, notify.js) also bypasses RLS.
-- ------------------------------------------------------------
ALTER TABLE contacts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrollments       ENABLE ROW LEVEL SECURITY;
ALTER TABLE refresh_signups   ENABLE ROW LEVEL SECURITY;
ALTER TABLE programs          ENABLE ROW LEVEL SECURITY;
ALTER TABLE confidant_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE sms_consent_log   ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admin_staff_read_contacts" ON contacts
  FOR SELECT TO authenticated USING (is_admin_or_staff());
CREATE POLICY "admin_staff_read_enrollments" ON enrollments
  FOR SELECT TO authenticated USING (is_admin_or_staff());
CREATE POLICY "admin_staff_read_refresh_signups" ON refresh_signups
  FOR SELECT TO authenticated USING (is_admin_or_staff());
CREATE POLICY "admin_staff_read_programs" ON programs
  FOR SELECT TO authenticated USING (is_admin_or_staff());
CREATE POLICY "admin_staff_read_confidant_requests" ON confidant_requests
  FOR SELECT TO authenticated USING (is_admin_or_staff());
CREATE POLICY "admin_staff_read_sms_consent_log" ON sms_consent_log
  FOR SELECT TO authenticated USING (is_admin_or_staff());

-- Allow admin/staff to UPDATE customer records (e.g., fix names/phones)
CREATE POLICY "admin_staff_update_contacts" ON contacts
  FOR UPDATE TO authenticated USING (is_admin_or_staff());
CREATE POLICY "admin_staff_update_refresh_signups" ON refresh_signups
  FOR UPDATE TO authenticated USING (is_admin_or_staff());


-- 5. RLS on user_roles — admin can manage all; staff can see their own
-- ------------------------------------------------------------
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admin_full_access_user_roles" ON user_roles
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "staff_read_own_role" ON user_roles
  FOR SELECT TO authenticated USING (user_id = auth.uid());


-- 6. RLS on customer_notes
-- ------------------------------------------------------------
ALTER TABLE customer_notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admin_staff_read_notes" ON customer_notes
  FOR SELECT TO authenticated USING (is_admin_or_staff());

CREATE POLICY "admin_staff_create_notes" ON customer_notes
  FOR INSERT TO authenticated
  WITH CHECK (is_admin_or_staff() AND author_id = auth.uid());

CREATE POLICY "authors_update_own_notes" ON customer_notes
  FOR UPDATE TO authenticated
  USING (is_admin_or_staff() AND author_id = auth.uid());

CREATE POLICY "authors_or_admin_delete_notes" ON customer_notes
  FOR DELETE TO authenticated
  USING (is_admin() OR (is_admin_or_staff() AND author_id = auth.uid()));


-- 7. Trigger to keep updated_at fresh on note edits
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_customer_notes_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_customer_notes_updated_at
  BEFORE UPDATE ON customer_notes
  FOR EACH ROW EXECUTE FUNCTION update_customer_notes_updated_at();


-- 8. Grant EXECUTE on helper functions to authenticated role
-- ------------------------------------------------------------
GRANT EXECUTE ON FUNCTION is_admin_or_staff() TO authenticated;
GRANT EXECUTE ON FUNCTION is_admin()          TO authenticated;
